clear;
clf;
clc;
img = double(imread('plaza1.png'));
%img_out = 255 * (img - we_min) / (we_max - we_min);
R = img(:,:,1);
G = img(:,:,2);
B = img(:,:,3);
R_norm = 255 * (R - min(R(:))) / (max(R(:)) - min(R(:)));
G_norm = 255 * (G - min(G(:))) / (max(G(:)) - min(G(:)));
B_norm = 255 * (B - min(B(:))) / (max(B(:)) - min(B(:)));
img_out = img;
img_out(:,:,1) = R_norm;
img_out(:,:,2) = G_norm;
img_out(:,:,3) = B_norm;
imshow(img_out/255);
subplot(2,2,1);
hist(vec(img_out(:,:,:)), 100);
title('R+G+B');
subplot(2,2,2);
hist(vec(R_norm), 100);
title('R');
subplot(2,2,3);
hist(vec(G_norm), 100);
title('G');
subplot(2,2,4);
hist(vec(B_norm), 100);
title('B');
