clear;
clf;
clc;
img = double(imread('plaza1.png'));
we_min = min(img(:));
we_max = max(img(:));
img_out = 255 * (img - we_min) / (we_max - we_min);
R = img_out(:,:,1);
G = img_out(:,:,2);
B = img_out(:,:,3);
%imshow(img_out/255);
subplot(2,2,1);
hist(vec(img_out(:,:,:)), 100);
title('R+G+B');
subplot(2,2,2);
hist(vec(R), 100);
title('R');
subplot(2,2,3);
hist(vec(G), 100);
title('G');
subplot(2,2,4);
hist(vec(B), 100);
title('B');
